name: Build & Deploy (Production)

on:
  push:
    branches:
      - main
    paths:
      - 'packages/api/**'
#      - 'packages/web/**'
#      - 'packages/axios-config/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Deploy
        run: echo "Deployed"
